[tool.poetry]
name = "repl_python3_BOJ-1"
version = "0.1.0"
description = ""
authors = ["blackgreenc0329 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
sympy = "^1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
